version: '3'

services:
  app:
    build:
      context: .
    container_name: booking_service_app
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://booking_service_mongodb:27017/test
    ports:
      - "4000:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: booking_service_mongodb
    ports:
      - "27017:27017"
