version: '3'

services:
  app:
    build:
      context: .
    container_name: booking_service_app
    environment:
      - MONGO_HOST=booking_service_mongodb
      - MONGO_DB=test
      - MONGO_INITDB_ROOT_USERNAME=pera1
      - MONGO_INITDB_ROOT_PASSWORD=pera1
    ports:
      - "4000:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: booking_service_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_DB=test
      - MONGO_INITDB_ROOT_USERNAME=pera1
      - MONGO_INITDB_ROOT_PASSWORD=pera1
